-- =========================================================
-- 📊 DATA WAREHOUSE ANALYTICS PROJECT
-- 👩‍💻 Author: Prerna Kumari
-- 🛠 Tools Used: SQL Server (SSMS), Power BI
-- =========================================================
-- 🔹 Project Overview:
-- This project focuses on designing a structured data warehouse
-- using a star schema approach and performing SQL-based analysis
-- to generate meaningful business insights.
-- The data is organized into dimension and fact tables to support
-- efficient querying and reporting.
-- =========================================================
-- 🗄️ DATABASE & SCHEMA DETAILS
-- =========================================================
-- Database Name: DataWarehouseAnalytics
-- Schema: gold
-- Tables:
-- 1. gold.dim_customers  -> Stores customer-related information
-- 2. gold.dim_products   -> Stores product-related information
-- 3. gold.fact_sales     -> Stores transactional sales data

-- =========================================================
-- 🔍 ANALYSIS PERFORMED USING SQL
-- =========================================================

-- 1️⃣ Exploratory Data Analysis (EDA)
--    - Identified youngest and oldest customers using birthdate
-- 2️⃣ Measure Exploration (Aggregate Analysis)
--    - Total Sales
--    - Total Quantity Sold
--    - Average Price
--    - Total Orders
--    - Total Products
--    - Total Customers
-- 3️⃣ Magnitude Analysis (Distribution & Comparison)
--    - Total customers by country
--    - Total customers by gender
--    - Total products by category
--    - Average cost per category
--    - Total revenue by category
--    - Revenue generated by each customer
--    - Distribution of sold items across countries
-- 4️⃣ Ranking Analysis
--    - Top 5 products generating highest revenue
--    - Bottom 5 products generating lowest revenue
-- =========================================================
-- 📊 NOTE:
-- Further analysis and insights are visualized using Power BI
-- dashboards including:
-- - Executive Overview
-- - Customer Analysis
-- - Product Analysis
-- - Sales Trend Analysis
-- =========================================================
-- 🚀 SQL SCRIPT STARTS BELOW
-- =========================================================


CREATE SCHEMA gold

SELECT TOP (1000) [customer_key]
      ,[customer_id]
      ,[customer_number]
      ,[first_name]
      ,[last_name]
      ,[country]
      ,[marital_status]
      ,[gender]
      ,[birthdate]
      ,[create_date]
  FROM [DataWarehouseAnalytics].[gold].[dim_customers]
------------------------------------------------------------------------------------------------------------
SELECT TOP (1000) [product_key]
      ,[product_id]
      ,[product_number]
      ,[product_name]
      ,[category_id]
      ,[category]
      ,[subcategory]
      ,[maintenance]
      ,[cost]
      ,[product_line]
      ,[start_date]
  FROM [DataWarehouseAnalytics].[gold].[dim_products]
----------------------------------------------------------------------------------------------------------------------------------
SELECT TOP (1000) [order_number]
      ,[product_key]
      ,[customer_key]
      ,[order_date]
      ,[shipping_date]
      ,[due_date]
      ,[sales_amount]
      ,[quantity]
      ,[price]
  FROM [DataWarehouseAnalytics].[gold].[fact_sales]
------------------------------------------------------------------------------------------------------------------------------
--if string than it is dimension
--if nummeric it is facts
 select distinct category from gold.dim_products
 select distinct sales_amount from gold.fact_sales
 select distinct product_name from gold.dim_products
 select distinct AVG(datediff(year,birthdate,GETDATE()))
 as Avg_Age from gold.dim_customers
------------------------------------------------------------------------------------------------------------------------------
--Explore all object in the databse
select* from INFORMATION_SCHEMA.TABLES
--Explore all column in the database
select* from INFORMATION_SCHEMA.COLUMNS where
TABLE_NAME= 'dim_customers'
---------------------------------------------------------------------------------------------------------------------------------
  
--explore all countries our customers come from
SELECT DISTINCT country FROM gold.dim_customers;

--explore all the category 'The major divisions'
SELECT DISTINCT category, subcategory,product_name from gold.dim_products;

--DATE EXPLORATION
--Find the date of the first and last order
--how many years of sales are available
SELECT MIN(order_date)AS first_order_date , max(order_date)AS last_order_date,
DATEDIFF(month,MIN(order_date),MAX(order_date))
AS order_range_years
FROM gold.fact_sales;

--find the youngest and the oldest customers
select MIN(birthdate)as oldest_customer, MAX(birthdate)as youngest_customers,
DATEDIFF(YEAR,MIN(birthdate),GETDATE())AS oldest_age,
DATEDIFF(YEAR,MAX(birthdate),GETDATE())AS youngest_age,
DATEDIFF(year,MIN(birthdate),MAX(birthdate)) as date_diff
from gold.dim_customers;
-------------------------------------------------------------------------------------------------------------------------
--Measures Exploration
--Aggregate Function

--FIND THE Total sales
SELECT Sum(sales_amount)as Total_sales FROM gold.fact_sales
--Find how many items are sold
select sum(quantity) AS Total_Quantity from gold.fact_sales
--Find the average selling price
Select AVG(price) as Avg_price from gold.fact_sales
--Find the total number of orders--repetation of orders
SELECT COUNT(order_number)as total_order FROM gold.fact_sales
--no count of repeted orders
SELECT COUNT(DISTINCT(order_number))AS total_order FROM gold.fact_sales
--Find the total number of products
select  COUNT(product_name)from gold.dim_products
select COUNT(distinct(product_key)) from gold.dim_products
--Find the Total numbers of Customers
select COUNT(customer_key)from gold.dim_customers
--Find the total number of customers that has placed an order
select count( distinct customer_key) from gold.fact_sales
-----------------------------------------------------------------------------------------------------------------------------
  
--Generate a Report that shows all key metrices of the Business
select  'Total Sales' AS measure_name,SUM(sales_amount) AS measure_value from gold.fact_sales
UNION ALL
select 'Total Quantity' AS measure_name ,sum(quantity) AS measure_value from gold.fact_sales
UNION ALL
Select'Avg Price' AS measure_name ,AVG(price)from gold.fact_sales
UNION ALL
SELECT 'Total order'AS measure_name,COUNT(DISTINCT(order_number)) FROM gold.fact_sales
UNION ALL
select 'Total Product'AS measure_name ,COUNT(distinct(product_key)) from gold.dim_products
UNION ALL
select 'Total Customer'AS measure_name,COUNT(customer_key)from gold.dim_customers
--------------------------------------------------------------------------------------------------------------------------------------

--MAGNITUDE ANALYSIS
--Find total customers by countries
SELECT country,COUNT(customer_key)AS total_customers 
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

--Find total customers by gender
SELECT gender,COUNT(customer_key)AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

--Find Total products by category
SELECT category,COUNT(product_key)as total_products FROM gold.dim_products
GROUP BY category
order by total_products desc

--What is the average costs in each category
SELECT category,AVG(cost)as avg_costs FROM gold.dim_products
GROUP BY category
order by avg_costs desc

--What is the total revenue generated for each category
SELECT p.category,SUM(f.sales_amount)Total_revenue FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
on p.product_key=f.product_key
group by p.category order by Total_revenue desc

--Find total revenue generated by each customers
SELECT c.customer_key,c.first_name,c.last_name,
SUM(f.sales_amount)Total_revenue FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
on c.customer_key=f.customer_key
group by c.customer_key,c.first_name,c.last_name 
order by Total_revenue desc

--What is the distribution of sold items across countries
SELECT c.country,
SUM(f.quantity)Total_sold_items FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
on c.customer_key=f.customer_key
group by c.country
order by Total_sold_items desc

----------------------------------------------------------------------------------------------------------------------
--RANKING ANALYSIS
--Which 5 products generate the highest revenue
SELECT TOP 5 p.product_name,
SUM(f.sales_amount)Total_revenue FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
on p.product_key=f.product_key
group by p.product_name order by Total_revenue desc

--Which are the 5 worst-performing products in terms of sales
SELECT  TOP 5 p.product_name,
SUM(f.sales_amount)Total_revenue FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
on p.product_key=f.product_key
group by p.product_name order by Total_revenue ASC





